# Generated by Django 4.2.20 on 2025-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="title"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="description"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("TD", "Por hacer"),
                            ("IP", "En progreso"),
                            ("C", "Completada"),
                        ],
                        default="TD",
                        max_length=2,
                        verbose_name="estado",
                    ),
                ),
            ],
        ),
    ]
