# Generated by Django 4.2.20 on 2025-03-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="description"
            ),
        ),
    ]
